### ISSUE TITLE
How's Categories used here?

### ISSUE THREAD

**Issue by analytically** [dkuppitz/sql2gremlin#6]
SELECT * FROM Categories -> g.V().hasLabel("category").valueMap()

should be 

SELECT * FROM category -> g.V().hasLabel("category").valueMap()

**Comment by analytically** [comment]
So you need to maintain a map plural to singular somewhere?

**Comment by analytically** [comment]
There are more strange things in your SQL syntax I find.

**Comment by dkuppitz** [comment]
The SQL queries are based on the original Northwind database, which uses plural table names.

**Comment by analytically** [comment]
Sure, but 'table names' do not exist in TinkerPop.

**Comment by dkuppitz** [comment]
And SQL doesn't exist in TinkerPop. If you want to see the original results: copy & paste the SQL queries into your SQL management studio. If you want to see TinkerPop results: Copy & paste the Gremlin queries into your Gremlin console. It's that simple.
